name: Deploy App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare VPS folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SERVERUSER }}
          key: ${{ secrets.SERVERSSHKEY }}
          script: |
            set -e
            APP_DIR="/apps/testing-backend-deployement"
            mkdir -p "$APP_DIR"
            rm -rf "$APP_DIR"/* "$APP_DIR"/.[!.]* "$APP_DIR"/..?* || true

      - name: Upload app to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SERVERUSER }}
          key: ${{ secrets.SERVERSSHKEY }}
          source: ".,!.git,!.github"
          target: "/apps/testing-backend-deployement"

      - name: Restart app (docker compose)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SERVERUSER }}
          key: ${{ secrets.SERVERSSHKEY }}
          script: |
            set -e
            cd /apps/testing-backend-deployement
            docker compose down || true
            docker compose up -d --build